### PR TITLE
Use Avanon Pyenv community role to install Pyenv

### PR DESCRIPTION
**Pull request by danypr92**
Add default Pyenv vars to set the global Python interpreter to 3.8.2 and
the Odoo python interpreter to 3.7.7.

### CODE REVIEW

**Comment by enricostano** [comment]
@danypr92 @cesarlr how should we manage upgrades of existing Odoo instances related to this?

**Comment by cesarlr** [comment]
> @danypr92 @cesarlr how should we manage upgrades of existing Odoo instances related to this?

It's a manual process, so we can only document it

**Comment by danypr92** [comment]
> @danypr92 @cesarlr how should we manage upgrades of existing Odoo instances related to this?

I think that we can run the provision over these outdated servers and the new Python interpreter and virtualenv will be successfully installed. The old virtualenv remains in the server, but if we don't use them we can delete them in the future...

@enricostano are you asking by how we can use this new strategy in the old servers or how can we purge the old virtualenv strategy?

**Comment by enricostano** [comment]
I just want to understand what needs to be done to make an existent inventory compatible to this change. It seems that nothing, it's not a problem if the old venv will still be there IMHO.

Maybe we can just try the process later in local with some existing inventory.

**Comment by enricostano** [comment]
@cesarlr @danypr92 what about the systemd unit? Should we point to the pyenv venv binary now?

**Comment by danypr92** [comment]
> @cesarlr @danypr92 what about the systemd unit? Should we point to the pyenv venv binary now?

We are updating the [`odoo_role_odoo_venv_path`](https://github.com/coopdevs/odoo-role/pull/78/files#diff-7eeda618087b49ae876084ab6c73fdbbR10) var to point to the new virtualenv. This var is used in the systemd unit to execute the correct Python interpreter:

https://github.com/coopdevs/odoo-role/blob/636997c1f0c0d4dd3d12af8775aa71f394501fb8/defaults/main.yml#L30

**Pull request merged**
