### PR TITLE
Stop using auxilar role for pyenv management

### PR DESCRIPTION
**Pull request by cesarlr**

### CODE REVIEW

**Comment by danypr92** [comment]
Why do we stop to use a community role?

**Comment by enricostano** [comment]
> Why do we stop to use a community role?

@danypr92 it was really difficult to call that role from this other role. We ended up just executing what we needed.

**Comment by danypr92** [comment]
> > Why do we stop to use a community role?
> 
> @danypr92 it was really difficult to call that role from this other role. We ended up just executing what we needed.

I don't understand... It's difficult because is a dependency of a role?

**Comment by enricostano** [comment]
> > > Why do we stop to use a community role?
> > 
> > 
> > @danypr92 it was really difficult to call that role from this other role. We ended up just executing what we needed.
> 
> I don't understand... It's difficult because is a dependency of a role?

Yep, there was a mix between the import vs include thing (external role always executing first), variable picking, and a couple things more. We were dedicating too much time to it.

**Pull request merged**
